// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CapsuleCloth

#include "ClothCommon.hlsl"

RWStructuredBuffer<Particle> Particles;
RWByteAddressBuffer PositionDeltas;
StructuredBuffer<Capsule> Capsules;

float collisionDamping = 0.1f;
float collisionCompliance = 0.0f;

void AtomicAddFloat(uint addr, float value)
{
    uint expected = PositionDeltas.Load(addr);
    for (;;)
    {
        float oldVal = asfloat(expected);
        float newVal = oldVal + value;
        uint desired = asuint(newVal);

        uint original;
        PositionDeltas.InterlockedCompareExchange(addr, expected, desired, original);

        if (original == expected)
            break;

        expected = original;
    }
}

void AtomicAddFloat3(uint index, float3 v)
{
    AtomicAddFloat(AddressOf(index, 0), v.x);
    AtomicAddFloat(AddressOf(index, 1), v.y);
    AtomicAddFloat(AddressOf(index, 2), v.z);
}

uint numParticles;
uint numIterations;
uint numSubSteps;
uint numCapsules;
float dt;
float Spacing;

[numthreads(256, 1, 1)]
void CapsuleCloth(uint id : SV_DispatchThreadID)
{
    if (id >= numParticles)
        return;
    
    float skinWidth = Spacing * 0.25f;

    Particle p = Particles[id];
    if (p.invMass == 0.0f)
        return;

    float3 pos = p.position;

    float dt_comp = dt / numSubSteps;

    
    for (uint c = 0; c < numCapsules; ++c)
    {
        Capsule col = Capsules[c];

        float3 ab = col.hemisphereB - col.hemisphereA;

        float abLenSq = dot(ab, ab);

        if (abLenSq < 1e-6f)
            continue;

        float t = saturate(dot(p.position - col.hemisphereA, ab) / abLenSq);

        float3 closestPoint = col.hemisphereA + ab * t;
        
        float3 d = p.position - closestPoint;
        
        float distanceDot = dot(d, d);
        
        float radi = col.radius + skinWidth;
        
        if (distanceDot >= radi * radi)
            continue;
        
        float dist = sqrt(distanceDot);
        
        if (dist < 1e-6f)
            continue;
        
        float3 n = d / dist;
        
        float penetration = radi - dist;
        
        
        float wCloth = p.invMass;
        float wCapsule = 0;
        float wSum = wCloth + wCapsule;

        float alpha = collisionCompliance / (dt_comp * dt_comp);

        float lambda = penetration / (wSum + alpha);

        float3 corr = lambda * n;

        float3 vrel = p.velocity - col.velocity;

        float normalVel = dot(vrel, n);
        corr = min(length(corr), Spacing) * n;
        
        AtomicAddFloat3(id, corr);
    }
    
    Particles[id] = p;

}
